variable "azure_database_mysql_flexible_server_resource_group" {}
variable "azure_database_mysql_flexible_server_name" {}
variable "azure_database_mysql_flexible_server_location" {}
variable "azure_database_mysql_flexible_server_version" {}
variable "azure_database_mysql_flexible_server_sku_name" {}
variable "azure_database_mysql_flexible_server_node_kv_name" {}
variable "azure_database_mysql_flexible_server_node_kv_rg_name" {}
variable "azure_database_mysql_flexible_server_ds_storage_account_name" {}
variable "azure_database_mysql_flexible_server_ds_sa_resource_group_name" {}
variable "azure_database_mysql_flexible_server_ds_law_name" {}
variable "azure_database_mysql_flexible_server_ds_law_resource_group_name" {}
variable "azure_database_mysql_flexible_server_meta_store_db_name" {}
variable "azure_database_mysql_flexible_server_amc_db_name" {}
variable "azure_database_mysql_flexible_server_pe_location" {}
variable "azure_database_mysql_flexible_server_subnet_name" {}
variable "azure_database_mysql_flexible_server_vnet_name" {}
variable "azure_database_mysql_flexible_server_vnet_resource_group_name" {}
variable "azure_database_mysql_flexible_server_zone" {}
variable "azure_database_mysql_flexible_server_backup_retention_days" {}
variable "azure_database_mysql_flexible_server_geo_redundant_backup_enabled" {}
variable "azure_database_mysql_flexible_server_storage_size" {}
variable "azure_database_mysql_flexible_server_io_scaling_enabled" {}
variable "azure_database_mysql_flexible_server_auto_grow_enabled" {}
variable "tags" {}
